const UI_STRINGS: Record<string, Record<string, string>> = {
  en: {
    signals: "signals",
    directory: "directory",
    readingIn: "reading in:",
    myTower: "my tower",
    allNeighborhoods: "all neighborhoods",
    crossLangHeader: "these people cannot read each other. the system connected them.",
    patternsDetected: "CROSS-LANGUAGE PATTERNS DETECTED",
    active: "active",
    noPatterns: "no cross-language patterns yet",
    noPatternsDesc: "when multiple languages mention the same person, place, or issue, it surfaces here.",
    reportSomething: "report something",
    rawReports: "raw reports",
    posts: "posts",
    languages: "languages",
    signal: "SIGNAL",
    strongCorroboration: "STRONG CORROBORATION",
    contributing: "CONTRIBUTING REPORTS",
    corroborationDesc: "Independent reports from people who cannot read each other. Corroboration, not consensus.",
    invisibleUntil: "This pattern was invisible until",
    communitiesReported: "communities reported independently.",
    independentReports: "independent reports across",
    mentionThis: "mention this",
    collapse: "collapse",
    reports: "reports",
    findMoreContext: "find more context",
    takeAction: "take action",
    communitiesFlagged: "independent communities flagged this. File a formal complaint:",
    submitReport: "submit report",
    processing: "processing...",
    enterIdentity: "enter any number as your identity key",
    identityExplainer: "hashed into an anonymous alias. never stored. never displayed.",
    reportPlaceholder: "report in any language -- a tip, a warning, a question...",
    speak: "speak",
    stop: "stop",
    listening: "listening...",
    pipelineReceipt: "pipeline receipt",
    translate: "translate",
    otherLanguages: "other languages",
    save: "save",
    saved: "saved",
    from: "from",
  },
  es: {
    signals: "senales",
    directory: "directorio",
    readingIn: "leyendo en:",
    myTower: "mi torre",
    allNeighborhoods: "todos los barrios",
    crossLangHeader: "estas personas no pueden leerse entre si. el sistema las conecto.",
    patternsDetected: "PATRONES MULTILINGUES DETECTADOS",
    active: "activos",
    noPatterns: "aun no hay patrones multilingues",
    noPatternsDesc: "cuando varios idiomas mencionan a la misma persona, lugar o problema, aparece aqui.",
    reportSomething: "reportar algo",
    rawReports: "reportes sin procesar",
    posts: "publicaciones",
    languages: "idiomas",
    signal: "SENAL",
    strongCorroboration: "CORROBORACION FUERTE",
    contributing: "REPORTES CONTRIBUYENTES",
    corroborationDesc: "Reportes independientes de personas que no pueden leerse entre si. Corroboracion, no consenso.",
    invisibleUntil: "Este patron era invisible hasta que",
    communitiesReported: "comunidades reportaron independientemente.",
    independentReports: "reportes independientes en",
    mentionThis: "mencionan esto",
    collapse: "cerrar",
    reports: "reportes",
    findMoreContext: "buscar mas contexto",
    takeAction: "tomar accion",
    communitiesFlagged: "comunidades independientes senalaron esto. Presenta una queja formal:",
    submitReport: "enviar reporte",
    processing: "procesando...",
    enterIdentity: "ingresa cualquier numero como tu clave de identidad",
    identityExplainer: "convertido en un alias anonimo. nunca almacenado. nunca mostrado.",
    reportPlaceholder: "reporta en cualquier idioma -- un dato, una advertencia, una pregunta...",
    speak: "hablar",
    stop: "parar",
    listening: "escuchando...",
    pipelineReceipt: "recibo del sistema",
    translate: "traducir",
    otherLanguages: "otros idiomas",
    save: "guardar",
    saved: "guardado",
    from: "de",
  },
  zh: {
    signals: "信号",
    directory: "目录",
    readingIn: "阅读语言:",
    myTower: "我的塔",
    allNeighborhoods: "所有社区",
    crossLangHeader: "这些人无法阅读彼此的语言。系统将他们连接起来。",
    patternsDetected: "检测到跨语言模式",
    active: "活跃",
    noPatterns: "暂无跨语言模式",
    noPatternsDesc: "当多种语言提到同一个人、地点或问题时，会在这里显示。",
    reportSomething: "报告",
    rawReports: "原始报告",
    posts: "条帖子",
    languages: "种语言",
    signal: "信号",
    strongCorroboration: "强力佐证",
    contributing: "相关报告",
    corroborationDesc: "来自互不相识的人的独立报告。这是佐证，不是共识。",
    invisibleUntil: "这个模式在",
    communitiesReported: "个社区独立报告之前是不可见的。",
    independentReports: "条独立报告，涉及",
    mentionThis: "提到了这个",
    collapse: "收起",
    reports: "条报告",
    findMoreContext: "查找更多信息",
    takeAction: "采取行动",
    communitiesFlagged: "个独立社区标记了此问题。提交正式投诉：",
    submitReport: "提交报告",
    processing: "处理中...",
    enterIdentity: "输入任意数字作为身份密钥",
    identityExplainer: "将被转换为匿名别名。绝不存储，绝不显示。",
    reportPlaceholder: "用任何语言报告 -- 线索、警告、问题...",
    speak: "说话",
    stop: "停止",
    listening: "正在收听...",
    pipelineReceipt: "处理回执",
    translate: "翻译",
    otherLanguages: "其他语言",
    save: "保存",
    saved: "已保存",
    from: "来自",
  },
};

export function t(lang: string, key: string): string {
  return UI_STRINGS[lang]?.[key] ?? UI_STRINGS.en[key] ?? key;
}
